# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sfr_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SFR(object):
    def setupUi(self, SFR):
        SFR.setObjectName("SFR")
        SFR.resize(943, 573)
        self.centralwidget = QtWidgets.QWidget(SFR)
        self.centralwidget.setObjectName("centralwidget")
        self.load_image = QtWidgets.QPushButton(self.centralwidget)
        self.load_image.setGeometry(QtCore.QRect(10, 150, 71, 23))
        self.load_image.setObjectName("load_image")
        self.roi = QtWidgets.QLabel(self.centralwidget)
        self.roi.setGeometry(QtCore.QRect(10, 190, 60, 60))
        self.roi.setText("")
        self.roi.setObjectName("roi")
        self.roi_title = QtWidgets.QLineEdit(self.centralwidget)
        self.roi_title.setGeometry(QtCore.QRect(10, 260, 60, 20))
        self.roi_title.setAutoFillBackground(False)
        self.roi_title.setAlignment(QtCore.Qt.AlignCenter)
        self.roi_title.setObjectName("roi_title")
        self.load_ocef_lut = QtWidgets.QPushButton(self.centralwidget)
        self.load_ocef_lut.setGeometry(QtCore.QRect(10, 10, 201, 23))
        self.load_ocef_lut.setObjectName("load_ocef_lut")
        self.ocef_lut = QtWidgets.QTextBrowser(self.centralwidget)
        self.ocef_lut.setGeometry(QtCore.QRect(10, 40, 201, 101))
        self.ocef_lut.setObjectName("ocef_lut")
        self.ocef_formula = QtWidgets.QLineEdit(self.centralwidget)
        self.ocef_formula.setGeometry(QtCore.QRect(350, 10, 311, 20))
        self.ocef_formula.setObjectName("ocef_formula")
        self.ocef_formula_title = QtWidgets.QLineEdit(self.centralwidget)
        self.ocef_formula_title.setGeometry(QtCore.QRect(250, 10, 91, 20))
        self.ocef_formula_title.setObjectName("ocef_formula_title")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 40, 411, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plot_ocef = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plot_ocef.setContentsMargins(0, 0, 0, 0)
        self.plot_ocef.setObjectName("plot_ocef")
        self.centroids_formula = QtWidgets.QLineEdit(self.centralwidget)
        self.centroids_formula.setGeometry(QtCore.QRect(390, 260, 271, 20))
        self.centroids_formula.setObjectName("centroids_formula")
        self.centroids_title = QtWidgets.QLineEdit(self.centralwidget)
        self.centroids_title.setGeometry(QtCore.QRect(250, 260, 131, 20))
        self.centroids_title.setObjectName("centroids_title")
        self.ocef_result_title = QtWidgets.QLineEdit(self.centralwidget)
        self.ocef_result_title.setGeometry(QtCore.QRect(80, 260, 60, 20))
        self.ocef_result_title.setAlignment(QtCore.Qt.AlignCenter)
        self.ocef_result_title.setObjectName("ocef_result_title")
        self.ocef_result = QtWidgets.QLabel(self.centralwidget)
        self.ocef_result.setGeometry(QtCore.QRect(80, 190, 60, 60))
        self.ocef_result.setText("")
        self.ocef_result.setObjectName("ocef_result")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 290, 211, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plot_ESF = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plot_ESF.setContentsMargins(0, 0, 0, 0)
        self.plot_ESF.setObjectName("plot_ESF")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(250, 290, 211, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plot_LSF = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plot_LSF.setContentsMargins(0, 0, 0, 0)
        self.plot_LSF.setObjectName("plot_LSF")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(490, 290, 211, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.plot_e_SFR = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.plot_e_SFR.setContentsMargins(0, 0, 0, 0)
        self.plot_e_SFR.setObjectName("plot_e_SFR")
        self.plot_ESF_title = QtWidgets.QLineEdit(self.centralwidget)
        self.plot_ESF_title.setGeometry(QtCore.QRect(10, 500, 211, 20))
        self.plot_ESF_title.setAlignment(QtCore.Qt.AlignCenter)
        self.plot_ESF_title.setObjectName("plot_ESF_title")
        self.plot_LSF_title = QtWidgets.QLineEdit(self.centralwidget)
        self.plot_LSF_title.setGeometry(QtCore.QRect(250, 500, 211, 20))
        self.plot_LSF_title.setAlignment(QtCore.Qt.AlignCenter)
        self.plot_LSF_title.setObjectName("plot_LSF_title")
        self.plot_e_SFR_title = QtWidgets.QLineEdit(self.centralwidget)
        self.plot_e_SFR_title.setGeometry(QtCore.QRect(490, 500, 211, 20))
        self.plot_e_SFR_title.setAlignment(QtCore.Qt.AlignCenter)
        self.plot_e_SFR_title.setObjectName("plot_e_SFR_title")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(720, 290, 211, 201))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.plot_SFR = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.plot_SFR.setContentsMargins(0, 0, 0, 0)
        self.plot_SFR.setObjectName("plot_SFR")
        self.plot_SFR_title = QtWidgets.QLineEdit(self.centralwidget)
        self.plot_SFR_title.setGeometry(QtCore.QRect(720, 500, 211, 20))
        self.plot_SFR_title.setAlignment(QtCore.Qt.AlignCenter)
        self.plot_SFR_title.setObjectName("plot_SFR_title")
        self.roi_diff = QtWidgets.QLabel(self.centralwidget)
        self.roi_diff.setGeometry(QtCore.QRect(150, 190, 60, 60))
        self.roi_diff.setText("")
        self.roi_diff.setObjectName("roi_diff")
        self.roi_diff_title = QtWidgets.QLineEdit(self.centralwidget)
        self.roi_diff_title.setGeometry(QtCore.QRect(150, 260, 60, 20))
        self.roi_diff_title.setAlignment(QtCore.Qt.AlignCenter)
        self.roi_diff_title.setObjectName("roi_diff_title")
        self.FontTest = QtWidgets.QLineEdit(self.centralwidget)
        self.FontTest.setGeometry(QtCore.QRect(730, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.FontTest.setFont(font)
        self.FontTest.setAutoFillBackground(False)
        self.FontTest.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.FontTest.setFrame(False)
        self.FontTest.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FontTest.setObjectName("FontTest")
        self.FontTest_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.FontTest_2.setGeometry(QtCore.QRect(730, 50, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.FontTest_2.setFont(font)
        self.FontTest_2.setAutoFillBackground(False)
        self.FontTest_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.FontTest_2.setFrame(False)
        self.FontTest_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FontTest_2.setObjectName("FontTest_2")
        SFR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SFR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 943, 23))
        self.menubar.setObjectName("menubar")
        SFR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SFR)
        self.statusbar.setObjectName("statusbar")
        SFR.setStatusBar(self.statusbar)

        self.retranslateUi(SFR)
        QtCore.QMetaObject.connectSlotsByName(SFR)

    def retranslateUi(self, SFR):
        _translate = QtCore.QCoreApplication.translate
        SFR.setWindowTitle(_translate("SFR", "MainWindow"))
        self.load_image.setText(_translate("SFR", "2.载入图像"))
        self.load_ocef_lut.setText(_translate("SFR", "1.载入OCEF LUT"))
        self.FontTest.setText(_translate("SFR", "Author：卢佳"))
        self.FontTest_2.setText(_translate("SFR", "E-mail：757055058@qq.com"))
